<?php

/**
 * @file
 * The hook implementations for the fences block.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\block\Entity\Block;
use Drupal\fences_block\FencesBlock;

/**
 * Implements hook_theme_registry_alter().
 * // #webksde#JP20171211: Hack: This is killing custom theme overrides: => Removed <=
 * https://www.drupal.org/project/2856428/issues/2929951
 */
//function fences_block_theme_registry_alter(array &$theme_registry) {
  //  $path = drupal_get_path('module', 'fences_block');
  //  $theme_registry['block']['path'] = $path . '/templates';
//}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function fences_block_form_block_form_alter(array &$form, FormStateInterface $form_state) {
  FencesBlock::addConfigForm($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function fences_block_form_block_form_alter(array &$form, FormStateInterface $form_state) {
  FencesBlock::addConfigForm($form, $form_state);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function fences_block_preprocess_block(array &$variables) {
  FencesBlock::preprocess($variables);
}
